/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as InventionsRouteImport } from './routes/inventions'
import { Route as FoundryRouteImport } from './routes/foundry'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const InventionsRoute = InventionsRouteImport.update({
  id: '/inventions',
  path: '/inventions',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundryRoute = FoundryRouteImport.update({
  id: '/foundry',
  path: '/foundry',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/contact': typeof ContactRoute
  '/foundry': typeof FoundryRoute
  '/inventions': typeof InventionsRoute
  '/investors': typeof InvestorsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/contact': typeof ContactRoute
  '/foundry': typeof FoundryRoute
  '/inventions': typeof InventionsRoute
  '/investors': typeof InvestorsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blueprint': typeof BlueprintRoute
  '/contact': typeof ContactRoute
  '/foundry': typeof FoundryRoute
  '/inventions': typeof InventionsRoute
  '/investors': typeof InvestorsRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blueprint'
    | '/contact'
    | '/foundry'
    | '/inventions'
    | '/investors'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blueprint'
    | '/contact'
    | '/foundry'
    | '/inventions'
    | '/investors'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/blueprint'
    | '/contact'
    | '/foundry'
    | '/inventions'
    | '/investors'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlueprintRoute: typeof BlueprintRoute
  ContactRoute: typeof ContactRoute
  FoundryRoute: typeof FoundryRoute
  InventionsRoute: typeof InventionsRoute
  InvestorsRoute: typeof InvestorsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventions': {
      id: '/inventions'
      path: '/inventions'
      fullPath: '/inventions'
      preLoaderRoute: typeof InventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundry': {
      id: '/foundry'
      path: '/foundry'
      fullPath: '/foundry'
      preLoaderRoute: typeof FoundryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlueprintRoute: BlueprintRoute,
  ContactRoute: ContactRoute,
  FoundryRoute: FoundryRoute,
  InventionsRoute: InventionsRoute,
  InvestorsRoute: InvestorsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
